server:
  port: 8001

mybatis:
  type-aliases-package: com.wys.redislearn.entity
  mapper-locations: classpath:Mapper/*.xml

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/redislearn?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: root
  redis:
    host: 47.99.119.199
    port: 6379
    database: 0
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1
        min-idle: 0

logging:
  level:
    root: info
    com.wys.redislearn.dao: debug
